# Generated by Django 3.2 on 2021-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='series',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
