# Generated by Django 3.2 on 2021-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_nsehistoricaldata_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='close_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='high_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='last_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='low_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='open_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='prev_close_currency',
        ),
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='total_traded_value_currency',
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='last',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='prev_close',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='total_traded_value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
