# Generated by Django 3.2 on 2021-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210613_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='last',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='prev_close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='total_traded_value',
            field=models.FloatField(),
        ),
    ]
