# Generated by Django 3.2 on 2021-06-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210616_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSETechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nsehistoricaldata',
            name='technicals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stocks.nsetechnical'),
        ),
    ]
