# Generated by Django 3.2 on 2021-06-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210617_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsetechnical',
            old_name='mfi',
            new_name='momentum_rsi',
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='momentum_stoch_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='momentum_stoch_rsi_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='momentum_stoch_rsi_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ema_fast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ema_slow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ichimoku_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ichimoku_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ichimoku_base',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_ichimoku_conv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_macd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_macd_diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_macd_signal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_sma_fast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_sma_slow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_visual_ichimoku_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='trend_visual_ichimoku_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbhi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volatility_bbw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volume_adi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='volume_mfi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='technicals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.nsetechnical'),
        ),
    ]
