# Generated by Django 3.2 on 2021-06-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20210619_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsehistoricaldata',
            name='technicals',
        ),
        migrations.AddField(
            model_name='nsetechnical',
            name='nse_historical_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.nsehistoricaldata'),
            preserve_default=False,
        ),
    ]
