# Generated by Django 3.2 on 2021-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_nsehistoricaldata_technicals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='technicals',
            field=models.BooleanField(default=False),
        ),
    ]
