# Generated by Django 3.2 on 2021-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_nsehistoricaldata_technicals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='last',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
