# Generated by Django 3.2 on 2021-07-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_nsehistoricaldata_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsehistoricaldata',
            name='prev_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
